# Generated by Django 4.2.7 on 2025-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
